# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df9a85a45be611839383b97d39a2cbe41332c5ff828edf6457896782448a3b036c544c273a43cc05c1a13645987f8395c4393421694f0c58b05cf10881883f41

test:
  secret_key_base: dc6cefc983dd4a9d9cee3376a5896b101b1d365f054151387a7c70be05e19c7370f10174a321d7584d0e788bfce8e0f57c0da5065b4db7a2272d73ef0025e611

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
